addons:
  hosts:
  - node1
before_install:
- if [ "$TRAVIS_OS_NAME" == "osx" ];        then sed -i '' 's/<gib.enabled>true/<gib.enabled>false/'
  $TRAVIS_BUILD_DIR/pom.xml;        else sed -i 's/<gib.enabled>true/<gib.enabled>false/'
  $TRAVIS_BUILD_DIR/pom.xml;        fi
- rvm use 2.1.5 --install
- nvm install 0.12.2
- nvm use 0.12.2
before_script:
- if [ "$TRAVIS_OS_NAME" == "osx" ];    then sed -i '' 's/<gib.enabled>false/<gib.enabled>true/'
  $TRAVIS_BUILD_DIR/pom.xml;    else sed -i 's/<gib.enabled>false/<gib.enabled>true/'
  $TRAVIS_BUILD_DIR/pom.xml;    fi
cache:
  directories:
  - $HOME/.m2/repository
  - $HOME/.rvm
  - $NVM_DIR
dist: trusty
env:
- MODULES=storm-client
- MODULES=storm-server
- MODULES=storm-core
- MODULES='!storm-client,!storm-server,!storm-core'
- MODULES='INTEGRATION-TEST'
install: /bin/bash ./dev-tools/travis/travis-install.sh `pwd`
jdk:
- oraclejdk8
language: java
script:
- touch /tmp/NOW
- echo GIBSTUDYSTART $(date)
- /bin/bash ./dev-tools/travis/travis-script.sh `pwd` $MODULES
- echo GIBSTUDYEND $(date)
- cd $TRAVIS_BUILD_DIR
- echo TESTNUM $(find . -name TEST-*.xml -newer /tmp/NOW | wc -l)
sudo: true
